storage:
  dbPath: /data/db
net:
  port: 27777
  bindIp: 0.0.0.0
replication:
  replSetName: wonders-rs
setParameter:
  searchIndexManagementHostAndPort: search:27028
  mongotHost: search:27028
  skipAuthenticationToSearchIndexManagementServer: false
  useGrpcForSearch: true
security:
  authorization: enabled
  keyFile: /etc/mongo-keyfile
